services:
  pointofsale:
    image: mysql:latest
    restart: always
    container_name: pos
    environment:
      MYSQL_DATABASE: 'pointofsale'
      MYSQL_USER: 'javase'
      MYSQL_PASSWORD: 'javase'
      MYSQL_ROOT_PASSWORD: 'javase'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /var/lib/mysql
