services:
  javase:
    image: mysql:latest
    restart: always
    container_name: javase
    environment:
      MYSQL_DATABASE: 'javase'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      # HOST-PORT:CONTAINER-PORT
      - '3308:3306'
    expose:
      - '3306'
      - '3308'
 
